_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 49
                - 54
                - 55
                - 105
            "2":
                - 49
                - 54
                - 55
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
